package be.unamur.fpgen.generation;

import be.unamur.fpgen.AbstractItem;
import be.unamur.fpgen.HasAuthor;
import be.unamur.fpgen.author.Author;
import be.unamur.fpgen.message.MessageTopicEnum;
import be.unamur.fpgen.message.MessageTypeEnum;
import be.unamur.fpgen.prompt.Prompt;
import be.unamur.fpgen.utils.DateUtil;

import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * a Generation represent a set of items that are generated by the system
 * it's always composed of a set of elements that are generated by the system
 * those elements can be messages or conversation depending on de generation type
 * A prompt has been used for the generation
 */
public class Generation extends AbstractItem implements HasAuthor {
    // members
    private final String generationId;
    private final GenerationTypeEnum generationType;
    private final Author author;
    private final String details;
    private final Integer quantity;
    private final MessageTypeEnum type;
    private final MessageTopicEnum topic;
    private final Prompt prompt;
    private final Set<AbstractItem> itemList = new HashSet<>();


    private Generation(Builder builder) {
        super(builder.getId(), builder.getCreationDate(), builder.getModificationDate());
        generationId = builder.generationId;
        generationType = builder.generationType;
        author = builder.author;
        details = builder.details;
        quantity = builder.quantity;
        type = builder.type;
        topic = builder.topic;
        prompt = builder.prompt;
        itemList.addAll(builder.itemList);
    }

    public GenerationTypeEnum getGenerationType() {
        return generationType;
    }

    public String getGenerationId() {
        return generationId;
    }

    public Author getAuthor() {
        return author;
    }

    public String getDetails() {
        return details;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public MessageTypeEnum getType() {
        return type;
    }

    public MessageTopicEnum getTopic() {
        return topic;
    }

    public Prompt getPrompt() {
        return prompt;
    }

    public Set<AbstractItem> getItemList() {
        return itemList;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static final class Builder extends AbstractItemBuilder<Builder> {
        private String generationId;
        private GenerationTypeEnum generationType;
        private Author author;
        private String details;
        private Integer quantity;
        private MessageTypeEnum type;
        private MessageTopicEnum topic;
        private Prompt prompt;
        private Set<AbstractItem> itemList = new HashSet<>();

        private Builder() {
        }

        public Builder withGenerationId(String val) {
            generationId = val;
            return this;
        }

        public Builder withGenerationType(GenerationTypeEnum val) {
            generationType = val;
            return this;
        }

        public Builder withAuthor(Author val) {
            author = val;
            return this;
        }

        public Builder withDetails(String val) {
            details = val;
            return this;
        }

        public Builder withQuantity(Integer val) {
            quantity = val;
            return this;
        }

        public Builder withType(MessageTypeEnum val) {
            type = val;
            return this;
        }

        public Builder withTopic(MessageTopicEnum val) {
            topic = val;
            return this;
        }

        public Builder withPrompt(Prompt val) {
            prompt = val;
            return this;
        }

        public Builder withItemList(Set<AbstractItem> val) {
            itemList = val;
            return this;
        }

        public Generation build() {
            generationId = generateGenerationId(GenerationTypeEnum.INSTANT_MESSAGE.equals(generationType) ? "IM" : "C");
            return new Generation(this);
        }

        public String returnBatchOrSingle(){
            return this.quantity > 1 ? "BATCH" : "SINGLE";
        }

        /**
         * @overview: generateGenerationId is a method that generates a unique identifier for a generation
         * @param generationType
         * @return String
         */
        public String generateGenerationId(final String generationType) {
            return String.format("%s-%s-%s-%s", generationType, this.returnBatchOrSingle(), this.author.getTrigram(), DateUtil.convertOffsetDateTimeMillisToString(OffsetDateTime.now()));
        }

        @Override
        protected Builder self() {
            return this;
        }
    }
}
