volumes:
  db_data_fpgen:
    driver: local
  keycloak_data_fpgen:
    driver: local

networks:
  keycloak_network_fpgen:
    driver: bridge

services:
  postgresql:
    image: postgres:17.4
    volumes:
      - db_data_fpgen:/var/lib/postgresql/data_fpgen
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_DB: fpgen
      POSTGRES_USER: fpgen
      POSTGRES_PASSWORD: fpgen
    ports:
      - 5432:5432
    networks:
      - keycloak_network_fpgen

  keycloak:
    image: bitnami/keycloak:26.1.4
    volumes:
      - ./keycloak-import:/opt/bitnami/keycloak/data/import
    environment:
      KEYCLOAK_DATABASE_NAME: fpgen
      KEYCLOAK_DATABASE_USER: fpgen
      KEYCLOAK_DATABASE_PASSWORD: fpgen
      KEYCLOAK_DATABASE_SCHEMA: keycloak
      KEYCLOAK_HOSTNAME: localhost
      KEYCLOAK_HOSTNAME_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOG_LEVEL: info
      KEYCLOAK_EXTRA_ARGS: --import-realm
      KEYCLOAK_FRONTEND_URL: http://localhost:8080
    depends_on:
      - postgresql
    ports:
      - 8080:8080
      - 7443:7443
    networks:
      - keycloak_network_fpgen

  backend:
    image: fpgen/application:backend_1.0.0
    ports:
      - 8000:8000
    depends_on:
      - postgresql
    networks:
      - keycloak_network_fpgen
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/fpgen?currentSchema=generation
      SPRING_DATASOURCE_USERNAME: fpgen
      SPRING_DATASOURCE_PASSWORD: fpgen
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # CORS
      APP_CORS_ALLOWED_ORIGINS: http://localhost:4200

      # Keycloak
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: FPGEN
      KEYCLOAK_CLIENT_ID: fpgen_app
      KEYCLOAK_CLIENT_UUID: d67bfeb3-7b48-488f-a777-4cfc4eb457b9
      KEYCLOAK_ADMIN_USERNAME: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/realms/FPGEN
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/FPGEN/protocol/openid-connect/certs

  frontend:
    image: fpgen/application:frontend_1.0.0
    ports:
      - 4200:4200
    depends_on:
      - keycloak
      - backend
    networks:
      - keycloak_network_fpgen